### ISSUE TITLE
Return from Transfer

### ISSUE THREAD

**Issue by skilesare** [NatLabs/icrc1#1]
While this is technically correct:

```

        /// Transfers the given amount of tokens from the sender to the recipient
        icrc1_transfer : shared (TransferArgs) -> async Result.Result<Balance, TransferError>;
```
because Balance is a Nat....it is kind of confusing.   There should be a BlockNumber of type Nat and use that here as the return is the block number of the new transaction and not the balance of the account.

**Comment by tomijaga** [comment]
Hey @skilesare, I added an `index` field to the `Transaction` record and updated the code to return the transaction index instead of the balance: https://github.com/NatLabs/icrc1/commit/c49ae92b1c4d6f6f9042f9b79015d999f3384449
