### ISSUE TITLE
Github Workflow Secrets not being applied

### ISSUE THREAD

**Issue by receronp** [NatLabs/icrc1#15]
@tomijaga I am seeing the following error when my PR tries to run the Workflow tests. 
```shell
  echo "" > ./identity.pem
  echo ""
  dfx identity import icrc-ref-test ./identity.pem --storage-mode plaintext
  dfx identity use icrc-ref-test
  dfx identity whoami
  make ref-test
  shell: /usr/bin/bash -e {0}
  env:
    DFX_TELEMETRY_DISABLED: 1
```
![ref-test](https://github.com/NatLabs/icrc1/assets/20917211/c9a5fe7d-538c-47bd-bfe7-9c81f6920493)

Is there some config I am missing to enable secrets for this PR?
I see in the makefile that this is the one trying to be called:
```shell
echo "${{ secrets.IDENTITY_SSH }}" > ./identity.pem
```

I leave the action link below:
https://github.com/NatLabs/icrc1/actions/runs/5099151687/jobs/9166723292

**Comment by receronp** [comment]
Found this settings information:
![image](https://github.com/NatLabs/icrc1/assets/20917211/030ceaf3-fa65-4349-aef6-9a05c492c225)
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories

And also this Github issue:
https://github.com/openmainframeproject/feilong/issues/367

**Comment by tomijaga** [comment]
Hello @receronp, thanks for the info.
Unfortunately, the settings you provided are only applicable for private repos.
I'm working on granting external PRs access to secrets using the `pull_request_target` event mentioned in the GitHub issue at the end of your post.
I'll let you know when I've pushed a fix to the main branch.

**Comment by tomijaga** [comment]
Hey @receronp, 
I've pushed the fix to the `main` branch, so the workflow tests should work once you've merged the new changes to the pr branch.
