### ISSUE TITLE
Returned "Result" Type... #Ok or not #ok? 

### ISSUE THREAD

**Issue by atengberg** [NatLabs/icrc1#3]
Great work! 

While doing some related work, I noticed that the "official" [example repository](https://github.com/dfinity/ICRC-1/blob/main/ref/ICRC1.mo#L97) declares its `Result` type the way the ICP/NNS ledger canister does:

`public type Result<T, E> = { #Ok : T; #Err : E };`

Which is also how another [implementation](https://github.com/eimolad/eimolad_icrc-1/blob/main/src/ICRC-1_bronze/main.mo#L113) by @eimolad does it:

`public type TransferResult = {
  #Ok  : Tokens;
  #Err : TransferError;
};`

I'm not sure why #Ok/#Err is used over the base library's #ok/#err, but this would cause conflicts with future callers if one or the other is not consistently used. Maybe @skilesare knows which should be?

**Comment by tomijaga** [comment]
Hey @atengberg, thanks for pointing this out!

I looked into the [standard](https://github.com/dfinity/ICRC-1/blob/main/standards/ICRC-1/README.md#icrc1_transfer-) again and found the line with the `#Ok` and `#Err` result variant.
```
icrc1_transfer : (TransferArgs) -> (variant { Ok: nat; Err: TransferError; });
```

To keep this implementation in compliance with the ICRC-1 standard, I'll change the `Result` type and update the repo.

**Comment by eimolad** [comment]
Hi! Is everything OK on our side?



Пт, 20 янв. 2023 г. в 18:51, Tomi Jaga ***@***.***>:

**Comment by tomijaga** [comment]
Hey @atengberg, I've updated the function to use the `TransferResult` type instead of the `Result` type in the base module.

Let me know if there are any other problems with the implementation, and I'll update the code to address them.
